export const GET_TODOS_SUCCESS = 'GET_TODOS_SUCCESS';
export const GET_TODOS_ERROR = 'GET_TODOS_ERROR';

export const GET_TODO_SUCCESS = 'GET_TODO_SUCCESS';
export const GET_TODO_ERROR = 'GET_TODO_ERROR';

export const ADD_TODO_SUCCESS = 'ADD_TODO_SUCCESS';
export const ADD_TODO_ERROR = 'ADD_TODO_ERROR';

export const TOGGLE_TODO_SUCCESS = 'TOGGLE_TODO_SUCCESS';
export const TOGGLE_TODO_ERROR = 'TOGGLE_TODO_ERROR';

export const RESET_TODOS_SUCCESS = 'RESET_TODOS_SUCCESS';
export const RESET_TODOS_ERROR = 'RESET_TODOS_ERROR';

export const SET_FILTER = 'SET_FILTER';

export const RESET_ACTIVE_TODO = 'RESET_ACTIVE_TODO';

export const TOGGLE_ADD_MODAL = 'TOGGLE_ADD_MODAL';